### ISSUE TITLE
Formbuilder module "Publish" button unresponsive

### ISSUE THREAD

**Issue by wrenchit** [formtools/module-form_builder#18] opened 2018-04-19 22:38 UTC
Formbuilder module "Publish" button unresponsive.  Can go though entire process and path ways/website path checks out and permissions are good, however when you click on the save or publish button to add form to website, nothing happens.  No errors just nothing.

Please help.

**Comment by benkeen** [comment] 2018-04-24 03:02
Hi @wrenchit - you're not alone! A couple of other people noticed the same issue (just linked them here), and judging by the length of time that issue has been open, it's been around since the FT3 compatibility update. 

I'm just going to do some more testing. If I still can't reproduce it I'll try to come up with some suggestions on how we can debug it.

**Comment by benkeen** [comment] 2018-04-24 04:11
Would someone mind trying the following? 

- Open up Chrome. 
- On the Edit Form -> Publish tab for any form, click the "Publish this form as a new location" button.
- The modal should appear. 
- In Chrome, go to the View -> Developer -> Javascript Console menu item. That will show the "developer tools" section. Click on the Network tab. 
- Back in the modal, click on the publish button, fill in the fields and click publish. 
- Return to the developer tools. You should see a few requests in the panel appear. Take a look at the last one and post a screenshot here (or email me at ben.keen@gmail.com if you think any of it looks sensitive). 

![screen shot 2018-04-23 at 9 08 37 pm](https://user-images.githubusercontent.com/512116/39165719-bb6ace7c-473a-11e8-8e41-b5907474bea0.png)

If all goes well, the last request should look something like that: that shows the response from the server. 

I think in your cases there's a problem on the server which is returning some error which the front-end isn't handling. I'm curious to know what that is!

**Comment by paulg10me** [comment] 2018-04-24 12:26
I don't have the option to "Publish this form as a new location" in the publish tab.
![image](https://user-images.githubusercontent.com/22027544/39186650-1f00b312-4799-11e8-81ab-b9b8118a5378.png)

**Comment by benkeen** [comment] 2018-04-24 13:26
Oh sorry - click the "Publish this form" button instead. The label changes once you've published it once.

**Comment by paulg10me** [comment] 2018-04-24 15:43
Here is what I'm seeing in the developer tools. Not sure if I'm in the right place. Hope it's helpful.
![image](https://user-images.githubusercontent.com/22027544/39198240-92f4f09c-47b4-11e8-9905-dda300b069b8.png)

**Comment by paulg10me** [comment] 2018-04-24 15:46
![image](https://user-images.githubusercontent.com/22027544/39198451-1f2ff48a-47b5-11e8-9ecb-8e2aaeb9c17e.png)

**Comment by benkeen** [comment] 2018-04-24 17:30
mwahaha, that's great thanks! That gives me a good clue as to what's going on. I'll take a look at this tonight.

**Comment by benkeen** [comment] 2018-04-25 04:45
Hey @paulg10me, would you mind running the following query on your database, then try publishing a form again? I'm curious to know if you get the same error.

`ALTER TABLE `ft_module_form_builder_forms` CHANGE `offline_date` `offline_date` DATETIME NULL;`

(Be sure to change `ft_` with the database name with whatever database prefix you're using).

**Comment by paulg10me** [comment] 2018-04-25 14:16
This solved the problem for me. I am now able to publish forms.
Thanks for your help.

**Comment by benkeen** [comment] 2018-04-25 23:48
No problem! I'll get a new version of the module out shortly that'll contain a fix for this. 

I'll also try to set up my DB in a similar fashion to yours - possibly you have some sort of strict mode running which I don't, which explains why you'd see the error and not me. Clearly this setting isn't uncommon because it's affected several people.

**Closed** 2018-04-26 03:52 UTC
Labels: Bug
